// Generated by tools/release_version.py; edit release.json.
#pragma once
namespace botty {
inline constexpr char nativeVersion[]="01.007.000";
inline constexpr char nativeDisplayVersion[]="1.7.0";
}
