#!/usr/bin/env python3
"""Bake the bundled OFL font to native alpha masks; Pillow is a build-only tool."""
from pathlib import Path
import hashlib
from PIL import Image, ImageDraw, ImageFont
ROOT=Path(__file__).resolve().parents[1]
font_path=ROOT/'vendor/manrope/Manrope.ttf'
# Printable ASCII plus the separators and arrows used by the interface copy.
EXTRAS=[0xB7,0x2013,0x2014,0x2019,0x2022,0x2026,0x2192,0x2193]
CODES=list(range(32,127))+EXTRAS
# Two weights only: 600 for text and 800 for titles, at the existing sizes.
WEIGHTS=[600,800]
SIZES=[20,24,28,32,44,60,76]
data=bytearray(); faces=[]
for weight in WEIGHTS:
    for size in SIZES:
        font=ImageFont.truetype(str(font_path),size)
        font.set_variation_by_axes([weight])
        glyphs=[]
        for code in CODES:
            c=chr(code); left,top,right,bottom=font.getbbox(c)
            width,height=right-left,bottom-top
            image=Image.new('L',(max(1,width),max(1,height)))
            ImageDraw.Draw(image).text((-left,-top),c,font=font,fill=255)
            glyphs.append((len(data),width,height,left,top,round(font.getlength(c))))
            if width and height:data.extend(image.tobytes())
        faces.append((size,weight,glyphs))
(ROOT/'assets/ui-font.bin').write_bytes(data)
header='''// Generated by tools/build-font.py from Manrope (SIL OFL 1.1).
#pragma once
#include <array>
#include <cstdint>
namespace botty::font {
'''
header+=f'inline constexpr unsigned glyphCount={len(CODES)};\n'
header+='// Glyphs 0-94 are ASCII 32-126; the remaining glyphs map these code points.\n'
header+=f'inline constexpr std::array<char32_t,{len(EXTRAS)}> extras{{{{'+','.join(hex(code) for code in EXTRAS)+'}};\n'
header+='''struct Glyph { unsigned offset; unsigned short width,height; short left,top,advance; };
struct Face { unsigned size,weight; std::array<Glyph,glyphCount> glyphs; };
'''
header+=f'inline constexpr unsigned dataSize={len(data)};\n'
header+=f'inline constexpr std::array<Face,{len(faces)}> faces{{{{\n'
for size,weight,glyphs in faces:
    header+=f'    {{{size}, {weight}, {{{{\n'
    header+=''.join('        {'+','.join(map(str,g))+'},\n' for g in glyphs)
    header+='    }}},\n'
header+='}};\n}\n'
(ROOT/'src/font_data.hpp').write_text(header)
print('Font bytes:',len(data),'source SHA256:',hashlib.sha256(font_path.read_bytes()).hexdigest())
