"""Single public Botty+ version and its generated native identities."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
NATIVE_IDENTITY = {
    'titleId': 'PPSA99071',
    'contentId': 'UP9000-PPSA99071_00-BOTTYNATIVE00001',
    'conceptId': '99071',
    'masterVersion': '01.00',
    'applicationCategoryType': 0,
    'applicationDrmType': 'free',
    'downloadDataSize': 256,
}


def ps5_version(version):
    if not isinstance(version, str) or not re.fullmatch(r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)', version):
        raise ValueError('Expected a canonical major.minor.patch release version')
    major, minor, patch = map(int, version.split('.'))
    if major > 99 or minor > 999 or patch > 999:
        raise ValueError('Release version exceeds PS5 contentVersion bounds')
    return f'{major:02}.{minor:03}.{patch:03}'


def release_version(root=ROOT):
    record = json.loads((root / 'release.json').read_text())
    if set(record) != {'schema', 'version'} or type(record['schema']) is not int or record['schema'] != 1:
        raise ValueError('Invalid public release definition')
    ps5_version(record['version'])
    return record['version']


def generated_files(root=ROOT):
    version = release_version(root)
    native = ps5_version(version)
    param = json.loads((root / 'sce_sys/param.json').read_text())
    for key, expected in NATIVE_IDENTITY.items():
        if type(param.get(key)) is not type(expected) or param[key] != expected:
            raise ValueError(f'Invalid native identity field {key} in sce_sys/param.json')
    localized = param.get('localizedParameters', {})
    english = localized.get('en-US', {}) if isinstance(localized, dict) else {}
    if not isinstance(english, dict) or english.get('titleName') != 'Botty+':
        raise ValueError('Invalid native identity field localizedParameters.en-US.titleName in sce_sys/param.json')
    param['contentVersion'] = native
    return {
        root / 'src/version.hpp': '// Generated by tools/release_version.py; edit release.json.\n'
            '#pragma once\nnamespace botty {\n'
            f'inline constexpr char nativeVersion[]="{native}";\n'
            f'inline constexpr char nativeDisplayVersion[]="{version}";\n'
            '}\n',
        root / 'sce_sys/param.json': json.dumps(param, indent=2) + '\n',
        root / 'assets/build.txt': f'Botty+ {version}\nrTorrent download engine\n',
    }


def sync(root=ROOT, check=False):
    for path, content in generated_files(root).items():
        if check:
            if not path.is_file() or path.read_text() != content:
                raise ValueError('Stale generated release file: ' + str(path))
        else:
            path.write_text(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    sync(check=args.check)
    print('Botty+ release version verified' if args.check else 'Botty+ release version generated')
